package com.unmute.app.domain.model

/** Bundled core words used as prediction candidates when they aren't on any card. */
object CommonWords {
    val ENGLISH: List<String> = listOf(
        "a", "able", "about", "above", "across", "act", "action", "add", "after",
        "afternoon", "again", "against", "age", "ago", "agree", "air", "all",
        "allow", "almost", "alone", "along", "already", "also", "although", "always",
        "am", "among", "an", "and", "angry", "animal", "another", "answer", "any",
        "anyone", "anything", "apartment", "apple", "are", "area", "arm", "around",
        "arrive", "as", "ask", "at", "aunt", "autumn", "away", "baby", "back",
        "bad", "bag", "ball", "bank", "bathroom", "be", "beautiful", "because",
        "become", "bed", "bedroom", "been", "before", "began", "begin", "behind",
        "believe", "below", "best", "better", "between", "big", "bird", "birthday",
        "black", "blue", "board", "boat", "body", "book", "both", "bottle",
        "bottom", "box", "boy", "bread", "break", "breakfast", "bridge", "bright",
        "bring", "broke", "brother", "brought", "brown", "build", "building", "bus",
        "busy", "but", "buy", "by", "call", "came", "camera", "can", "cannot",
        "car", "care", "careful", "carry", "cat", "catch", "cause", "chair",
        "change", "cheap", "check", "child", "children", "city", "class", "clean",
        "clear", "climb", "clock", "close", "clothes", "cloud", "coat", "coffee",
        "cold", "college", "color", "come", "company", "computer", "cook", "cool",
        "corner", "could", "count", "country", "course", "cover", "cow", "cross",
        "cup", "cut", "dad", "dance", "dark", "day", "dead", "dear", "deep",
        "desk", "did", "die", "different", "difficult", "dinner", "dirty", "do",
        "doctor", "dog", "dollar", "done", "don't", "door", "down", "draw", "dream",
        "dress", "drink", "drive", "drop", "dry", "during", "each", "early",
        "earth", "east", "easy", "eat", "egg", "eight", "either", "else", "end",
        "enough", "even", "evening", "ever", "every", "everyone", "everything",
        "example", "excited", "exercise", "eye", "face", "fact", "fall", "family",
        "far", "farm", "fast", "father", "feel", "feet", "fell", "few", "field",
        "fight", "fill", "finally", "find", "fine", "finger", "finish", "fire",
        "first", "fish", "five", "fix", "floor", "fly", "food", "foot", "for",
        "found", "four", "free", "friend", "from", "front", "fruit", "full",
        "fun", "game", "garden", "gave", "get", "girl", "give", "glad", "glass",
        "go", "going", "gone", "good", "got", "great", "green", "ground", "group",
        "grow", "guess", "guy", "had", "hair", "half", "hand", "happen", "happy",
        "hard", "has", "hat", "have", "he", "head", "hear", "heard", "heart",
        "heavy", "held", "help", "her", "here", "high", "hill", "him", "himself",
        "his", "hold", "home", "hope", "horse", "hospital", "hot", "hour", "house",
        "how", "however", "huge", "hundred", "hungry", "hurry", "hurt", "i", "ice",
        "idea", "if", "important", "in", "inside", "instead", "into", "is", "it",
        "its", "job", "join", "juice", "jump", "just", "keep", "kept", "key",
        "kid", "kill", "kind", "kitchen", "knew", "know", "lady", "land",
        "language", "large", "last", "late", "later", "laugh", "lay", "lead",
        "learn", "leave", "left", "leg", "less", "let", "letter", "library",
        "life", "light", "like", "line", "list", "listen", "little", "live",
        "long", "look", "lose", "lost", "lot", "loud", "love", "low", "lunch",
        "made", "make", "man", "many", "map", "market", "maybe", "me", "mean",
        "meet", "men", "mess", "might", "mind", "minute", "miss", "money", "month",
        "moon", "more", "morning", "most", "mother", "mountain", "mouse", "mouth",
        "move", "movie", "much", "music", "must", "my", "name", "near", "need",
        "never", "new", "news", "next", "nice", "night", "nine", "no", "noise",
        "north", "nose", "not", "nothing", "now", "number", "nurse", "o'clock",
        "of", "off", "offer", "office", "often", "oh", "old", "on", "once",
        "one", "only", "open", "orange", "or", "order", "other", "our", "out",
        "outside", "over", "own", "page", "pain", "paint", "paper", "park", "part",
        "party", "pass", "past", "pay", "people", "perhaps", "person", "phone",
        "photo", "pick", "picture", "piece", "place", "plan", "plant", "play",
        "please", "point", "police", "poor", "possible", "power", "pretty",
        "probably", "problem", "pull", "push", "put", "question", "quick", "quiet",
        "quite", "radio", "rain", "ran", "rather", "reach", "read", "ready",
        "real", "really", "reason", "red", "remember", "rent", "rest", "restaurant",
        "rice", "rich", "ride", "right", "ring", "river", "road", "rock", "room",
        "round", "run", "sad", "said", "same", "save", "saw", "say", "school",
        "sea", "seat", "second", "see", "seem", "seen", "sell", "send", "sentence",
        "seven", "several", "shall", "she", "shirt", "shoe", "shop", "short",
        "should", "show", "sick", "side", "sing", "sister", "sit", "six", "size",
        "sleep", "slow", "small", "smart", "smell", "smile", "snow", "so", "some",
        "someone", "something", "sometimes", "son", "song", "soon", "sorry", "sound",
        "soup", "south", "space", "speak", "special", "spend", "sport", "spring",
        "stand", "star", "start", "station", "stay", "step", "still", "stop",
        "store", "story", "street", "strong", "student", "study", "such", "summer",
        "sun", "sure", "swim", "table", "take", "talk", "tall", "taste", "teach",
        "teacher", "team", "tell", "ten", "than", "thank", "that", "the", "their",
        "them", "then", "there", "these", "they", "thing", "think", "third",
        "this", "those", "though", "thought", "thousand", "three", "through",
        "throw", "ticket", "time", "tired", "to", "today", "together", "told",
        "tomorrow", "too", "took", "top", "town", "toy", "train", "travel",
        "tree", "trip", "trouble", "true", "try", "turn", "two", "uncle",
        "under", "understand", "until", "up", "us", "use", "very", "visit",
        "voice", "wait", "walk", "wall", "want", "warm", "was", "wash", "watch",
        "water", "way", "we", "wear", "weather", "week", "weekend", "well",
        "went", "were", "west", "what", "whatever", "when", "where", "whether",
        "which", "while", "white", "who", "whole", "why", "wife", "will",
        "win", "wind", "window", "winter", "wish", "with", "without", "woman",
        "women", "won", "word", "work", "world", "would", "write", "wrong",
        "wrote", "yard", "year", "yellow", "yes", "yet", "you", "young", "your",
        "zero",
    )

    val SPANISH: List<String> = listOf(
        "a", "abajo", "abrir", "abuelo", "abuela", "acabar", "aceptar", "agua",
        "ahí", "ahora", "al", "algo", "alguien", "algún", "alguno", "allá",
        "allí", "alto", "amar", "amigo", "amor", "andar", "animal", "año",
        "antes", "aquel", "aquí", "árbol", "así", "atención", "atrás", "aunque",
        "ayudar", "bajar", "bajo", "bailar", "bastante", "beber", "bien", "blanco",
        "bonito", "brazo", "bueno", "buscar", "cabeza", "cada", "caer", "café",
        "caliente", "calle", "caminar", "camisa", "campo", "cansado", "cara", "carne",
        "casa", "casi", "casar", "cerca", "cerrado", "chico", "cielo", "claro",
        "clase", "cocina", "coche", "coger", "color", "comer", "como", "cómo",
        "comprar", "comprender", "con", "conocer", "contento", "contestar", "contra", "corazón",
        "correr", "cosa", "cortar", "corto", "creer", "cruzar", "cuadro", "cuál",
        "cual", "cualquier", "cuando", "cuándo", "cuanto", "cuánto", "cuatro", "cubrir",
        "cuchara", "cuenta", "cuerpo", "cuidado", "cumplir", "dar", "de", "deber",
        "decidir", "decir", "dejar", "del", "demás", "dentro", "deporte", "derecho",
        "desayuno", "desde", "desear", "después", "día", "dibujo", "diez", "diferente",
        "difícil", "dinero", "dirección", "doctor", "dolor", "donde", "dónde", "dormir",
        "dos", "duro", "el", "él", "ella", "ellas", "ellos", "en",
        "encima", "encontrar", "entender", "entonces", "entrar", "entre", "entregar", "eres",
        "es", "esa", "escalera", "escribir", "escuchar", "escuela", "ese", "eso",
        "esos", "esperar", "está", "estación", "esta", "estar", "estas", "este",
        "esto", "estos", "estoy", "estudiar", "examen", "fácil", "falta", "familia",
        "feo", "fin", "flor", "fondo", "forma", "frío", "fruta", "fue",
        "fuego", "fuera", "fuerte", "gente", "gracias", "grande", "gritar", "guardar",
        "gusta", "gustar", "haber", "hacer", "hacia", "hablar", "hambre", "hasta",
        "hay", "he", "helado", "hermana", "hermano", "hija", "hijo", "historia",
        "hola", "hombre", "hora", "hoy", "hueso", "huevo", "ir", "irse",
        "izquierda", "joven", "juego", "jugar", "junto", "la", "lado", "lamentar",
        "lápiz", "largo", "las", "lavar", "le", "leer", "lejos", "lengua",
        "lento", "les", "letra", "levantar", "libro", "limpio", "lo", "loco",
        "los", "luego", "lugar", "luz", "llamar", "llegar", "llenar", "lleno",
        "llevar", "llorar", "llover", "mal", "malo", "mamá", "mandar", "mano",
        "mañana", "mapa", "mar", "más", "me", "médico", "medio", "mejor",
        "menos", "mesa", "meter", "mi", "miedo", "mientras", "mío", "mirar",
        "mismo", "mojado", "momento", "montaña", "morir", "mover", "muchacha", "muchacho",
        "mucho", "mujer", "mundo", "muy", "nada", "nadar", "nadie", "naranja",
        "nariz", "nacer", "natural", "negro", "ni", "ningún", "ninguno", "niño",
        "no", "noche", "nombre", "nos", "nosotros", "nuestro", "nueve", "nuevo",
        "número", "nunca", "o", "oír", "ojo", "oler", "olor", "once",
        "ordenar", "otoño", "otra", "otro", "padre", "pagar", "país", "pan",
        "papá", "papel", "para", "parar", "parecer", "pared", "parte", "pasar",
        "pato", "pequeño", "perder", "perezoso", "pero", "perro", "persona", "pescado",
        "pie", "piedra", "piel", "pierna", "piso", "plan", "plato", "playa",
        "plaza", "poco", "poder", "poner", "por", "porque", "posible", "pregunta",
        "premio", "primero", "primo", "probar", "problema", "pronto", "propio", "pueblo",
        "puerta", "pues", "punto", "que", "qué", "quedar", "querer", "queso",
        "quien", "quién", "quinto", "quitar", "rato", "razón", "recoger", "recordar",
        "regalar", "regalo", "reír", "repetir", "responder", "resto", "rico", "río",
        "robar", "rojo", "ropa", "rubio", "rueda", "saber", "sal", "sala",
        "salir", "salud", "saludo", "sano", "se", "secar", "seco", "seguir",
        "según", "segundo", "seis", "semana", "sentar", "sentido", "sentir", "señor",
        "señora", "ser", "servicio", "si", "sí", "silla", "sin", "siquiera",
        "sitio", "sobre", "sol", "solo", "sombra", "sonar", "soñar", "sopa",
        "sorprender", "subir", "sucio", "sueldo", "sueño", "suerte", "suyo", "tal",
        "también", "tampoco", "tan", "tarde", "tarea", "taza", "te", "temer",
        "temprano", "tender", "tener", "tercero", "terminar", "tierra", "ti", "tiempo",
        "tienda", "tierno", "tío", "tipo", "tirar", "título", "tocar", "todavía",
        "todo", "todos", "tomar", "trabajar", "trabajo", "traer", "tratar", "tren",
        "tres", "triste", "tu", "tú", "último", "un", "uno", "unos",
        "usar", "usted", "ustedes", "vacío", "valer", "venir", "vender", "ver",
        "verdad", "verde", "vestir", "vez", "viajar", "viaje", "viejo", "viento",
        "vivir", "volver", "voz", "y", "ya", "yo",
    )

    fun forLanguage(language: String): List<String> =
        if (language == "es") SPANISH else ENGLISH
}
