package com.unmute.app.domain.model

data class EmojiEntry(
    val emoji: String,
    val labelEn: String,
    val labelEs: String,
)

val EMOJI_LIBRARY: List<EmojiEntry> = listOf(
    EmojiEntry("😀", "grinning face", "cara sonriente"),
    EmojiEntry("😃", "smiling face with big eyes", "cara sonriente con ojos grandes"),
    EmojiEntry("😄", "smiling face with smiling eyes", "cara sonriente con ojos sonrientes"),
    EmojiEntry("😁", "beaming face with smiling eyes", "cara radiante con ojos sonrientes"),
    EmojiEntry("😆", "grinning squinting face", "cara sonriente con ojos apretados"),
    EmojiEntry("😅", "grinning face with sweat", "cara sonriente con sudor"),
    EmojiEntry("🤣", "rolling on the floor laughing", "riéndose a carcajadas"),
    EmojiEntry("😂", "face with tears of joy", "cara con lágrimas de alegría"),
    EmojiEntry("🙂", "slightly smiling face", "cara levemente sonriente"),
    EmojiEntry("🙃", "upside-down face", "cara al revés"),
    EmojiEntry("😉", "winking face", "cara guiñando un ojo"),
    EmojiEntry("😊", "smiling face with smiling eyes", "cara sonriente con ojos sonrientes"),
    EmojiEntry("😇", "smiling face with halo", "cara sonriente con aureola"),
    EmojiEntry("🥰", "smiling face with hearts", "cara sonriente con corazones"),
    EmojiEntry("😍", "smiling face with heart-eyes", "cara enamorada"),
    EmojiEntry("🤩", "star-struck", "cara maravillada"),
    EmojiEntry("😘", "face blowing a kiss", "cara mandando un beso"),
    EmojiEntry("😗", "kissing face", "cara besando"),
    EmojiEntry("😚", "kissing face with closed eyes", "cara besando con ojos cerrados"),
    EmojiEntry("😜", "winking face with tongue", "cara guiñando con lengua"),
    EmojiEntry("🤪", "zany face", "cara loca"),
    EmojiEntry("😝", "squinting face with tongue", "cara con lengua y ojos apretados"),
    EmojiEntry("😛", "face with tongue", "cara con lengua"),
    EmojiEntry("🤑", "money-mouth face", "cara con billetes en la boca"),
    EmojiEntry("🤗", "smiling face with open hands", "cara sonriente con manos abiertas"),
    EmojiEntry("🤭", "face with hand over mouth", "cara con la mano en la boca"),
    EmojiEntry("🤫", "shushing face", "cara pidiendo silencio"),
    EmojiEntry("🤔", "thinking face", "cara pensativa"),
    EmojiEntry("🤐", "zipper-mouth face", "cara con boca de cremallera"),
    EmojiEntry("🤨", "face with raised eyebrow", "cara con ceja levantada"),
    EmojiEntry("😐", "neutral face", "cara neutral"),
    EmojiEntry("😑", "expressionless face", "cara inexpresiva"),
    EmojiEntry("😶", "face without mouth", "cara sin boca"),
    EmojiEntry("😏", "smirking face", "cara de suficiencia"),
    EmojiEntry("😒", "unamused face", "cara de desaprobación"),
    EmojiEntry("🙄", "face with rolling eyes", "cara con ojos en blanco"),
    EmojiEntry("😬", "grimacing face", "cara de mueca"),
    EmojiEntry("🤥", "lying face", "cara de mentiroso"),
    EmojiEntry("😌", "relieved face", "cara aliviada"),
    EmojiEntry("😔", "pensive face", "cara pensativa"),
    EmojiEntry("😪", "sleepy face", "cara soñolienta"),
    EmojiEntry("🤤", "drooling face", "cara babeando"),
    EmojiEntry("😴", "sleeping face", "cara durmiendo"),
    EmojiEntry("😷", "face with medical mask", "cara con mascarilla médica"),
    EmojiEntry("🤒", "face with thermometer", "cara con termómetro"),
    EmojiEntry("🤕", "face with head-bandage", "cara con vendaje"),
    EmojiEntry("🤢", "nauseated face", "cara con náuseas"),
    EmojiEntry("🤮", "face vomiting", "cara vomitando"),
    EmojiEntry("🥵", "hot face", "cara con calor"),
    EmojiEntry("🥶", "cold face", "cara con frío"),
    EmojiEntry("🥴", "woozy face", "cara mareada"),
    EmojiEntry("😵", "dizzy face", "cara aturdida"),
    EmojiEntry("🤯", "exploding head", "cabeza explotando"),
    EmojiEntry("🤠", "cowboy hat face", "cara con sombrero de vaquero"),
    EmojiEntry("🥳", "partying face", "cara de fiesta"),
    EmojiEntry("😎", "smiling face with sunglasses", "cara con gafas de sol"),
    EmojiEntry("🤓", "nerd face", "cara de empollón"),
    EmojiEntry("🧐", "face with monocle", "cara con monóculo"),
    EmojiEntry("😕", "confused face", "cara confundida"),
    EmojiEntry("😟", "worried face", "cara preocupada"),
    EmojiEntry("🙁", "slightly frowning face", "cara levemente triste"),
    EmojiEntry("☹️", "frowning face", "cara triste"),
    EmojiEntry("😮", "face with open mouth", "cara con la boca abierta"),
    EmojiEntry("😯", "hushed face", "cara asombrada"),
    EmojiEntry("😲", "astonished face", "cara atónita"),
    EmojiEntry("😳", "flushed face", "cara sonrojada"),
    EmojiEntry("🥺", "pleading face", "cara suplicante"),
    EmojiEntry("😦", "frowning face with open mouth", "cara triste con la boca abierta"),
    EmojiEntry("😧", "anguished face", "cara angustiada"),
    EmojiEntry("😨", "fearful face", "cara asustada"),
    EmojiEntry("😰", "anxious face with sweat", "cara ansiosa con sudor"),
    EmojiEntry("😥", "sad but relieved face", "cara triste pero aliviada"),
    EmojiEntry("😢", "crying face", "cara llorando"),
    EmojiEntry("😭", "loudly crying face", "cara llorando a gritos"),
    EmojiEntry("😱", "face screaming in fear", "cara gritando de miedo"),
    EmojiEntry("😖", "confounded face", "cara confundida"),
    EmojiEntry("😣", "persevering face", "cara de esfuerzo"),
    EmojiEntry("😞", "disappointed face", "cara decepcionada"),
    EmojiEntry("😓", "downcast face with sweat", "cara abatida con sudor"),
    EmojiEntry("😩", "weary face", "cara cansada"),
    EmojiEntry("😫", "tired face", "cara agotada"),
    EmojiEntry("🥱", "yawning face", "cara bostezando"),
    EmojiEntry("😤", "face with steam from nose", "cara con vapor por la nariz"),
    EmojiEntry("😡", "pouting face", "cara enfadada"),
    EmojiEntry("😠", "angry face", "cara enojada"),
    EmojiEntry("🤬", "face with symbols on mouth", "cara con símbolos en la boca"),
    EmojiEntry("😈", "smiling face with horns", "cara sonriente con cuernos"),
    EmojiEntry("👿", "angry face with horns", "cara enojada con cuernos"),
    EmojiEntry("💀", "skull", "calavera"),
    EmojiEntry("☠️", "skull and crossbones", "calavera y huesos"),
    EmojiEntry("💩", "pile of poo", "caca"),
    EmojiEntry("🤡", "clown face", "cara de payaso"),
    EmojiEntry("👻", "ghost", "fantasma"),
    EmojiEntry("👽", "alien", "extraterrestre"),
    EmojiEntry("👾", "alien monster", "monstruo extraterrestre"),
    EmojiEntry("🤖", "robot", "robot"),
    EmojiEntry("😺", "grinning cat", "gato sonriente"),
    EmojiEntry("😸", "grinning cat with smiling eyes", "gato sonriente con ojos sonrientes"),
    EmojiEntry("😹", "cat with tears of joy", "gato con lágrimas de alegría"),
    EmojiEntry("😻", "smiling cat with heart-eyes", "gato enamorado"),
    EmojiEntry("😼", "cat with wry smile", "gato con sonrisa irónica"),
    EmojiEntry("😽", "kissing cat", "gato besando"),
    EmojiEntry("🙀", "weary cat", "gato cansado"),
    EmojiEntry("😿", "crying cat", "gato llorando"),
    EmojiEntry("😾", "pouting cat", "gato enfadado"),
    EmojiEntry("👋", "waving hand", "mano saludando"),
    EmojiEntry("🤚", "raised back of hand", "dorso de la mano"),
    EmojiEntry("🖐️", "hand with fingers splayed", "mano con dedos abiertos"),
    EmojiEntry("✋", "raised hand", "mano levantada"),
    EmojiEntry("🖖", "vulcan salute", "saludo vulcano"),
    EmojiEntry("👌", "OK hand", "gesto de OK"),
    EmojiEntry("🤌", "pinched fingers", "dedos pellizcando"),
    EmojiEntry("🤏", "pinching hand", "mano pellizcando"),
    EmojiEntry("✌️", "victory hand", "signo de victoria"),
    EmojiEntry("🤞", "crossed fingers", "dedos cruzados"),
    EmojiEntry("🤟", "love-you gesture", "gesto de te quiero"),
    EmojiEntry("🤘", "sign of the horns", "signo de los cuernos"),
    EmojiEntry("🤙", "call me hand", "mano de llamar"),
    EmojiEntry("👈", "backhand index pointing left", "índice apuntando a la izquierda"),
    EmojiEntry("👉", "backhand index pointing right", "índice apuntando a la derecha"),
    EmojiEntry("👆", "backhand index pointing up", "índice apuntando hacia arriba"),
    EmojiEntry("👇", "backhand index pointing down", "índice apuntando hacia abajo"),
    EmojiEntry("☝️", "index pointing up", "índice hacia arriba"),
    EmojiEntry("👍", "thumbs up", "pulgar arriba"),
    EmojiEntry("👎", "thumbs down", "pulgar abajo"),
    EmojiEntry("✊", "raised fist", "puño levantado"),
    EmojiEntry("👊", "oncoming fist", "puño hacia delante"),
    EmojiEntry("🤛", "left-facing fist", "puño hacia la izquierda"),
    EmojiEntry("🤜", "right-facing fist", "puño hacia la derecha"),
    EmojiEntry("👏", "clapping hands", "manos aplaudiendo"),
    EmojiEntry("🙌", "raising hands", "manos levantadas"),
    EmojiEntry("👐", "open hands", "manos abiertas"),
    EmojiEntry("🤲", "palms up together", "manos juntas hacia arriba"),
    EmojiEntry("🤝", "handshake", "apretón de manos"),
    EmojiEntry("🙏", "folded hands", "manos juntas"),
    EmojiEntry("💪", "flexed biceps", "bíceps"),
    EmojiEntry("🦾", "mechanical arm", "brazo mecánico"),
    EmojiEntry("🦶", "foot", "pie"),
    EmojiEntry("👂", "ear", "oreja"),
    EmojiEntry("👃", "nose", "nariz"),
    EmojiEntry("🧠", "brain", "cerebro"),
    EmojiEntry("🦷", "tooth", "diente"),
    EmojiEntry("👀", "eyes", "ojos"),
    EmojiEntry("👅", "tongue", "lengua"),
    EmojiEntry("👄", "mouth", "boca"),
    EmojiEntry("👤", "bust in silhouette", "silueta de persona"),
    EmojiEntry("👥", "busts in silhouette", "siluetas de personas"),
    EmojiEntry("🧑", "person", "persona"),
    EmojiEntry("👶", "baby", "bebé"),
    EmojiEntry("🧒", "child", "niño"),
    EmojiEntry("👦", "boy", "niño"),
    EmojiEntry("👧", "girl", "niña"),
    EmojiEntry("👨", "man", "hombre"),
    EmojiEntry("👩", "woman", "mujer"),
    EmojiEntry("🧓", "older person", "persona mayor"),
    EmojiEntry("👴", "old man", "anciano"),
    EmojiEntry("👵", "old woman", "anciana"),
    EmojiEntry("🙅", "person gesturing no", "persona haciendo gesto de no"),
    EmojiEntry("🙆", "person gesturing OK", "persona haciendo gesto de OK"),
    EmojiEntry("💁", "person tipping hand", "persona ofreciendo ayuda"),
    EmojiEntry("🙋", "person raising hand", "persona levantando la mano"),
    EmojiEntry("🧏", "deaf person", "persona sorda"),
    EmojiEntry("🙇", "person bowing", "persona inclinándose"),
    EmojiEntry("🤦", "person facepalming", "persona llevándose la mano a la cara"),
    EmojiEntry("🤷", "person shrugging", "persona encogiéndose de hombros"),
    EmojiEntry("💆", "person getting massage", "persona recibiendo masaje"),
    EmojiEntry("💇", "person getting haircut", "persona cortándose el pelo"),
    EmojiEntry("🚶", "person walking", "persona caminando"),
    EmojiEntry("🧍", "person standing", "persona de pie"),
    EmojiEntry("🧎", "person kneeling", "persona de rodillas"),
    EmojiEntry("🏃", "person running", "persona corriendo"),
    EmojiEntry("💃", "woman dancing", "mujer bailando"),
    EmojiEntry("🕺", "man dancing", "hombre bailando"),
    EmojiEntry("🧖", "person in steamy room", "persona en sauna"),
    EmojiEntry("🧗", "person climbing", "persona escalando"),
    EmojiEntry("🤺", "person fencing", "persona esgrimiendo"),
    EmojiEntry("🏇", "horse racing", "carrera de caballos"),
    EmojiEntry("🏄", "person surfing", "persona surfeando"),
    EmojiEntry("🚣", "person rowing boat", "persona remando"),
    EmojiEntry("🏊", "person swimming", "persona nadando"),
    EmojiEntry("🏋️", "person lifting weights", "persona levantando pesas"),
    EmojiEntry("🚴", "person biking", "persona en bicicleta"),
    EmojiEntry("🤸", "person cartwheeling", "persona haciendo volteretas"),
    EmojiEntry("🤽", "person playing water polo", "persona jugando waterpolo"),
    EmojiEntry("🤾", "person playing handball", "persona jugando balonmano"),
    EmojiEntry("🤹", "person juggling", "persona haciendo malabares"),
    EmojiEntry("🧘", "person in lotus position", "persona en posición de loto"),
    EmojiEntry("🛀", "person taking bath", "persona en la bañera"),
    EmojiEntry("🛌", "person in bed", "persona en la cama"),
    EmojiEntry("💌", "love letter", "carta de amor"),
    EmojiEntry("💘", "heart with arrow", "corazón con flecha"),
    EmojiEntry("💝", "heart with ribbon", "corazón con lazo"),
    EmojiEntry("💖", "sparkling heart", "corazón brillante"),
    EmojiEntry("💗", "growing heart", "corazón creciente"),
    EmojiEntry("💓", "beating heart", "corazón latiendo"),
    EmojiEntry("💞", "revolving hearts", "corazones girando"),
    EmojiEntry("💕", "two hearts", "dos corazones"),
    EmojiEntry("💔", "broken heart", "corazón roto"),
    EmojiEntry("❤️", "red heart", "corazón rojo"),
    EmojiEntry("🧡", "orange heart", "corazón naranja"),
    EmojiEntry("💛", "yellow heart", "corazón amarillo"),
    EmojiEntry("💚", "green heart", "corazón verde"),
    EmojiEntry("💙", "blue heart", "corazón azul"),
    EmojiEntry("💜", "purple heart", "corazón morado"),
    EmojiEntry("🖤", "black heart", "corazón negro"),
    EmojiEntry("🤍", "white heart", "corazón blanco"),
    EmojiEntry("💯", "hundred points", "cien puntos"),
    EmojiEntry("💢", "anger symbol", "símbolo de enfado"),
    EmojiEntry("💥", "collision", "explosión"),
    EmojiEntry("💦", "sweat droplets", "gotas de sudor"),
    EmojiEntry("💨", "dashing away", "nubes de velocidad"),
    EmojiEntry("💬", "speech balloon", "bocadillo de diálogo"),
    EmojiEntry("💭", "thought balloon", "bocadillo de pensamiento"),
    EmojiEntry("💤", "zzz", "zzz"),
    EmojiEntry("👓", "glasses", "gafas"),
    EmojiEntry("🕶️", "sunglasses", "gafas de sol"),
    EmojiEntry("🥽", "goggles", "gafas de protección"),
    EmojiEntry("👔", "necktie", "corbata"),
    EmojiEntry("👕", "t-shirt", "camiseta"),
    EmojiEntry("👖", "jeans", "vaqueros"),
    EmojiEntry("🧣", "scarf", "bufanda"),
    EmojiEntry("🧤", "gloves", "guantes"),
    EmojiEntry("🧥", "coat", "abrigo"),
    EmojiEntry("🧦", "socks", "calcetines"),
    EmojiEntry("👗", "dress", "vestido"),
    EmojiEntry("👘", "kimono", "kimono"),
    EmojiEntry("👙", "bikini", "biquini"),
    EmojiEntry("👚", "woman's clothes", "ropa de mujer"),
    EmojiEntry("👛", "purse", "monedero"),
    EmojiEntry("👜", "handbag", "bolso"),
    EmojiEntry("🎒", "backpack", "mochila"),
    EmojiEntry("👟", "running shoe", "zapatilla de deporte"),
    EmojiEntry("🥾", "hiking boot", "bota de senderismo"),
    EmojiEntry("👠", "high-heeled shoe", "zapato de tacón"),
    EmojiEntry("👑", "crown", "corona"),
    EmojiEntry("👒", "woman's hat", "sombrero de mujer"),
    EmojiEntry("🎩", "top hat", "sombrero de copa"),
    EmojiEntry("🎓", "graduation cap", "birrete de graduación"),
    EmojiEntry("🧢", "billed cap", "gorra"),
    EmojiEntry("💄", "lipstick", "pintalabios"),
    EmojiEntry("💍", "ring", "anillo"),
    EmojiEntry("💎", "gem stone", "gema"),
    EmojiEntry("🐶", "dog face", "cara de perro"),
    EmojiEntry("🐱", "cat face", "cara de gato"),
    EmojiEntry("🐭", "mouse face", "cara de ratón"),
    EmojiEntry("🐹", "hamster", "hámster"),
    EmojiEntry("🐰", "rabbit face", "cara de conejo"),
    EmojiEntry("🦊", "fox", "zorro"),
    EmojiEntry("🐻", "bear", "oso"),
    EmojiEntry("🐼", "panda", "panda"),
    EmojiEntry("🐨", "koala", "koala"),
    EmojiEntry("🐯", "tiger face", "cara de tigre"),
    EmojiEntry("🦁", "lion", "león"),
    EmojiEntry("🐮", "cow face", "cara de vaca"),
    EmojiEntry("🐷", "pig face", "cara de cerdo"),
    EmojiEntry("🐸", "frog", "rana"),
    EmojiEntry("🐵", "monkey face", "cara de mono"),
    EmojiEntry("🙈", "see-no-evil monkey", "mono que no ve"),
    EmojiEntry("🙉", "hear-no-evil monkey", "mono que no oye"),
    EmojiEntry("🙊", "speak-no-evil monkey", "mono que no habla"),
    EmojiEntry("🐒", "monkey", "mono"),
    EmojiEntry("🐔", "chicken", "pollo"),
    EmojiEntry("🐧", "penguin", "pingüino"),
    EmojiEntry("🐦", "bird", "pájaro"),
    EmojiEntry("🐤", "baby chick", "pollito"),
    EmojiEntry("🦆", "duck", "pato"),
    EmojiEntry("🦅", "eagle", "águila"),
    EmojiEntry("🦉", "owl", "búho"),
    EmojiEntry("🦜", "parrot", "loro"),
    EmojiEntry("🐊", "crocodile", "cocodrilo"),
    EmojiEntry("🐢", "turtle", "tortuga"),
    EmojiEntry("🦎", "lizard", "lagarto"),
    EmojiEntry("🐍", "snake", "serpiente"),
    EmojiEntry("🐉", "dragon", "dragón"),
    EmojiEntry("🦖", "T-Rex", "tiranosaurio"),
    EmojiEntry("🐳", "spouting whale", "ballena"),
    EmojiEntry("🐬", "dolphin", "delfín"),
    EmojiEntry("🐟", "fish", "pez"),
    EmojiEntry("🐠", "tropical fish", "pez tropical"),
    EmojiEntry("🦈", "shark", "tiburón"),
    EmojiEntry("🐙", "octopus", "pulpo"),
    EmojiEntry("🦑", "squid", "calamar"),
    EmojiEntry("🦀", "crab", "cangrejo"),
    EmojiEntry("🐚", "spiral shell", "caracola"),
    EmojiEntry("🐌", "snail", "caracol"),
    EmojiEntry("🦋", "butterfly", "mariposa"),
    EmojiEntry("🐛", "bug", "insecto"),
    EmojiEntry("🐜", "ant", "hormiga"),
    EmojiEntry("🐝", "honeybee", "abeja"),
    EmojiEntry("🐞", "lady beetle", "mariquita"),
    EmojiEntry("🕷️", "spider", "araña"),
    EmojiEntry("🦂", "scorpion", "escorpión"),
    EmojiEntry("💐", "bouquet", "ramo de flores"),
    EmojiEntry("🌸", "cherry blossom", "flor de cerezo"),
    EmojiEntry("🌹", "rose", "rosa"),
    EmojiEntry("🥀", "wilted flower", "flor marchita"),
    EmojiEntry("🌺", "hibiscus", "hibisco"),
    EmojiEntry("🌻", "sunflower", "girasol"),
    EmojiEntry("🌼", "blossom", "flor"),
    EmojiEntry("🌷", "tulip", "tulipán"),
    EmojiEntry("🌱", "seedling", "plántula"),
    EmojiEntry("🌲", "evergreen tree", "árbol de hoja perenne"),
    EmojiEntry("🌳", "deciduous tree", "árbol de hoja caduca"),
    EmojiEntry("🌴", "palm tree", "palmera"),
    EmojiEntry("🌵", "cactus", "cactus"),
    EmojiEntry("🌿", "herb", "hierba"),
    EmojiEntry("🍀", "four leaf clover", "trébol de cuatro hojas"),
    EmojiEntry("🍁", "maple leaf", "hoja de arce"),
    EmojiEntry("🍂", "fallen leaf", "hoja caída"),
    EmojiEntry("🍇", "grapes", "uvas"),
    EmojiEntry("🍈", "melon", "melón"),
    EmojiEntry("🍉", "watermelon", "sandía"),
    EmojiEntry("🍊", "tangerine", "mandarina"),
    EmojiEntry("🍋", "lemon", "limón"),
    EmojiEntry("🍌", "banana", "plátano"),
    EmojiEntry("🍍", "pineapple", "piña"),
    EmojiEntry("🥭", "mango", "mango"),
    EmojiEntry("🍎", "red apple", "manzana roja"),
    EmojiEntry("🍏", "green apple", "manzana verde"),
    EmojiEntry("🍐", "pear", "pera"),
    EmojiEntry("🍑", "peach", "melocotón"),
    EmojiEntry("🍒", "cherries", "cerezas"),
    EmojiEntry("🍓", "strawberry", "fresa"),
    EmojiEntry("🥝", "kiwi fruit", "kiwi"),
    EmojiEntry("🍅", "tomato", "tomate"),
    EmojiEntry("🥥", "coconut", "coco"),
    EmojiEntry("🥑", "avocado", "aguacate"),
    EmojiEntry("🍆", "eggplant", "berenjena"),
    EmojiEntry("🥔", "potato", "patata"),
    EmojiEntry("🥕", "carrot", "zanahoria"),
    EmojiEntry("🌽", "ear of corn", "mazorca de maíz"),
    EmojiEntry("🌶️", "hot pepper", "guindilla"),
    EmojiEntry("🥒", "cucumber", "pepino"),
    EmojiEntry("🥦", "broccoli", "brócoli"),
    EmojiEntry("🧄", "garlic", "ajo"),
    EmojiEntry("🧅", "onion", "cebolla"),
    EmojiEntry("🍄", "mushroom", "champiñón"),
    EmojiEntry("🥜", "peanuts", "cacahuetes"),
    EmojiEntry("🌰", "chestnut", "castaña"),
    EmojiEntry("🍞", "bread", "pan"),
    EmojiEntry("🥐", "croissant", "croissant"),
    EmojiEntry("🥨", "pretzel", "pretzel"),
    EmojiEntry("🥞", "pancakes", "panqueques"),
    EmojiEntry("🧀", "cheese wedge", "trozo de queso"),
    EmojiEntry("🍖", "meat on bone", "carne con hueso"),
    EmojiEntry("🍗", "poultry leg", "muslo de pollo"),
    EmojiEntry("🥩", "cut of meat", "corte de carne"),
    EmojiEntry("🥓", "bacon", "beicon"),
    EmojiEntry("🍔", "hamburger", "hamburguesa"),
    EmojiEntry("🍟", "french fries", "patatas fritas"),
    EmojiEntry("🍕", "pizza", "pizza"),
    EmojiEntry("🌭", "hot dog", "perrito caliente"),
    EmojiEntry("🥪", "sandwich", "sándwich"),
    EmojiEntry("🌮", "taco", "taco"),
    EmojiEntry("🌯", "burrito", "burrito"),
    EmojiEntry("🥙", "stuffed flatbread", "pan relleno"),
    EmojiEntry("🥚", "egg", "huevo"),
    EmojiEntry("🍳", "cooking", "cocinando"),
    EmojiEntry("🥘", "shallow pan of food", "paella"),
    EmojiEntry("🍲", "pot of food", "olla de comida"),
    EmojiEntry("🥗", "green salad", "ensalada"),
    EmojiEntry("🍿", "popcorn", "palomitas"),
    EmojiEntry("🧂", "salt", "sal"),
    EmojiEntry("🥫", "canned food", "comida en lata"),
    EmojiEntry("🍙", "rice ball", "bola de arroz"),
    EmojiEntry("🍚", "cooked rice", "arroz cocido"),
    EmojiEntry("🍛", "curry rice", "arroz con curry"),
    EmojiEntry("🍜", "steaming bowl", "tazón humeante"),
    EmojiEntry("🍝", "spaghetti", "espaguetis"),
    EmojiEntry("🍣", "sushi", "sushi"),
    EmojiEntry("🍤", "fried shrimp", "gamba frita"),
    EmojiEntry("🥟", "dumpling", "empanadilla"),
    EmojiEntry("🍦", "soft ice cream", "helado suave"),
    EmojiEntry("🍨", "ice cream", "helado"),
    EmojiEntry("🍩", "doughnut", "rosquilla"),
    EmojiEntry("🍪", "cookie", "galleta"),
    EmojiEntry("🎂", "birthday cake", "pastel de cumpleaños"),
    EmojiEntry("🍰", "shortcake", "bizcocho"),
    EmojiEntry("🧁", "cupcake", "magdalena"),
    EmojiEntry("🥧", "pie", "tarta"),
    EmojiEntry("🍫", "chocolate bar", "tableta de chocolate"),
    EmojiEntry("🍬", "candy", "caramelo"),
    EmojiEntry("🍭", "lollipop", "piruleta"),
    EmojiEntry("🍮", "custard", "flan"),
    EmojiEntry("🍯", "honey pot", "tarro de miel"),
    EmojiEntry("🍼", "baby bottle", "biberón"),
    EmojiEntry("🥛", "glass of milk", "vaso de leche"),
    EmojiEntry("☕", "hot beverage", "bebida caliente"),
    EmojiEntry("🍵", "teacup without handle", "taza de té"),
    EmojiEntry("🍾", "bottle with popping cork", "botella con corcho"),
    EmojiEntry("🍷", "wine glass", "copa de vino"),
    EmojiEntry("🍸", "cocktail glass", "copa de cóctel"),
    EmojiEntry("🍹", "tropical drink", "bebida tropical"),
    EmojiEntry("🍺", "beer mug", "jarra de cerveza"),
    EmojiEntry("🍻", "clinking beer mugs", "jarras chocando"),
    EmojiEntry("🥂", "clinking glasses", "copas chocando"),
    EmojiEntry("🥤", "cup with straw", "vaso con pajita"),
    EmojiEntry("🧃", "beverage box", "envase de bebida"),
    EmojiEntry("🍽️", "fork and knife with plate", "cubiertos con plato"),
    EmojiEntry("🍴", "fork and knife", "tenedor y cuchillo"),
    EmojiEntry("🥄", "spoon", "cuchara"),
    EmojiEntry("⚽", "soccer ball", "balón de fútbol"),
    EmojiEntry("⚾", "baseball", "pelota de béisbol"),
    EmojiEntry("🏀", "basketball", "baloncesto"),
    EmojiEntry("🏐", "volleyball", "voleibol"),
    EmojiEntry("🏈", "american football", "fútbol americano"),
    EmojiEntry("🎾", "tennis", "tenis"),
    EmojiEntry("🎳", "bowling", "bolos"),
    EmojiEntry("🏓", "ping pong", "ping-pong"),
    EmojiEntry("🏸", "badminton", "bádminton"),
    EmojiEntry("🥊", "boxing glove", "guante de boxeo"),
    EmojiEntry("🥋", "martial arts uniform", "uniforme de artes marciales"),
    EmojiEntry("⛳", "flag in hole", "banderín en hoyo"),
    EmojiEntry("🎣", "fishing pole", "caña de pescar"),
    EmojiEntry("🎽", "running shirt", "camiseta de correr"),
    EmojiEntry("🎯", "bullseye", "diana"),
    EmojiEntry("🪁", "kite", "cometa"),
    EmojiEntry("🎱", "pool 8 ball", "bola de billar"),
    EmojiEntry("🔮", "crystal ball", "bola de cristal"),
    EmojiEntry("🎮", "video game", "videojuego"),
    EmojiEntry("🕹️", "joystick", "mando de videojuego"),
    EmojiEntry("🎲", "game die", "dado"),
    EmojiEntry("🧩", "puzzle piece", "pieza de puzle"),
    EmojiEntry("🧸", "teddy bear", "osito de peluche"),
    EmojiEntry("♟️", "chess pawn", "peón de ajedrez"),
    EmojiEntry("🎪", "circus tent", "carpa de circo"),
    EmojiEntry("🎭", "performing arts", "artes escénicas"),
    EmojiEntry("🎨", "artist palette", "paleta de pintor"),
    EmojiEntry("🎬", "clapper board", "claqueta"),
    EmojiEntry("🎤", "microphone", "micrófono"),
    EmojiEntry("🎧", "headphone", "auriculares"),
    EmojiEntry("🎼", "musical score", "partitura"),
    EmojiEntry("🎹", "musical keyboard", "teclado musical"),
    EmojiEntry("🎸", "guitar", "guitarra"),
    EmojiEntry("🎺", "trumpet", "trompeta"),
    EmojiEntry("🎻", "violin", "violín"),
    EmojiEntry("🥁", "drum", "batería"),
    EmojiEntry("🎷", "saxophone", "saxofón"),
    EmojiEntry("🎵", "musical note", "nota musical"),
    EmojiEntry("🎶", "musical notes", "notas musicales"),
    EmojiEntry("🎫", "ticket", "entrada"),
    EmojiEntry("🎟️", "admission tickets", "entradas"),
    EmojiEntry("🎰", "slot machine", "máquina tragaperras"),
    EmojiEntry("🚗", "automobile", "coche"),
    EmojiEntry("🚕", "taxi", "taxi"),
    EmojiEntry("🚙", "sport utility vehicle", "todoterreno"),
    EmojiEntry("🚌", "bus", "autobús"),
    EmojiEntry("🏎️", "racing car", "coche de carreras"),
    EmojiEntry("🚓", "police car", "coche de policía"),
    EmojiEntry("🚑", "ambulance", "ambulancia"),
    EmojiEntry("🚒", "fire engine", "camión de bomberos"),
    EmojiEntry("🚚", "delivery truck", "camión de reparto"),
    EmojiEntry("🚜", "tractor", "tractor"),
    EmojiEntry("🛵", "motor scooter", "scooter"),
    EmojiEntry("🏍️", "motorcycle", "motocicleta"),
    EmojiEntry("🚲", "bicycle", "bicicleta"),
    EmojiEntry("🛴", "kick scooter", "patinete"),
    EmojiEntry("🚨", "police car light", "luz de policía"),
    EmojiEntry("🛸", "flying saucer", "platillo volante"),
    EmojiEntry("🚁", "helicopter", "helicóptero"),
    EmojiEntry("✈️", "airplane", "avión"),
    EmojiEntry("🚀", "rocket", "cohete"),
    EmojiEntry("🛰️", "satellite", "satélite"),
    EmojiEntry("🧭", "compass", "brújula"),
    EmojiEntry("🗺️", "world map", "mapa del mundo"),
    EmojiEntry("🏠", "house", "casa"),
    EmojiEntry("🏡", "house with garden", "casa con jardín"),
    EmojiEntry("🏢", "office building", "edificio de oficinas"),
    EmojiEntry("🏥", "hospital", "hospital"),
    EmojiEntry("🏦", "bank", "banco"),
    EmojiEntry("🏨", "hotel", "hotel"),
    EmojiEntry("🏫", "school", "escuela"),
    EmojiEntry("🏭", "factory", "fábrica"),
    EmojiEntry("🏰", "castle", "castillo"),
    EmojiEntry("💒", "wedding", "boda"),
    EmojiEntry("🗼", "Tokyo tower", "torre de Tokio"),
    EmojiEntry("🗽", "Statue of Liberty", "estatua de la Libertad"),
    EmojiEntry("⛪", "church", "iglesia"),
    EmojiEntry("🕌", "mosque", "mezquita"),
    EmojiEntry("⛲", "fountain", "fuente"),
    EmojiEntry("⛺", "tent", "tienda de campaña"),
    EmojiEntry("🌃", "night with stars", "noche estrellada"),
    EmojiEntry("🏙️", "cityscape", "paisaje urbano"),
    EmojiEntry("🌄", "sunrise over mountains", "amanecer en las montañas"),
    EmojiEntry("🌅", "sunrise", "amanecer"),
    EmojiEntry("🌇", "sunset", "atardecer"),
    EmojiEntry("♨️", "hot springs", "aguas termales"),
    EmojiEntry("⌚", "watch", "reloj de pulsera"),
    EmojiEntry("📱", "mobile phone", "teléfono móvil"),
    EmojiEntry("💻", "laptop computer", "ordenador portátil"),
    EmojiEntry("⌨️", "keyboard", "teclado"),
    EmojiEntry("🖥️", "desktop computer", "ordenador de sobremesa"),
    EmojiEntry("🖨️", "printer", "impresora"),
    EmojiEntry("🖱️", "computer mouse", "ratón de ordenador"),
    EmojiEntry("💾", "floppy disk", "disquete"),
    EmojiEntry("📀", "DVD", "DVD"),
    EmojiEntry("📷", "camera", "cámara"),
    EmojiEntry("📸", "camera with flash", "cámara con flash"),
    EmojiEntry("📹", "video camera", "videocámara"),
    EmojiEntry("🎥", "movie camera", "cámara de cine"),
    EmojiEntry("📞", "telephone receiver", "auricular de teléfono"),
    EmojiEntry("☎️", "telephone", "teléfono"),
    EmojiEntry("📺", "television", "televisión"),
    EmojiEntry("📻", "radio", "radio"),
    EmojiEntry("⏰", "alarm clock", "despertador"),
    EmojiEntry("🔋", "battery", "batería"),
    EmojiEntry("🔌", "electric plug", "enchufe"),
    EmojiEntry("💡", "light bulb", "bombilla"),
    EmojiEntry("🔦", "flashlight", "linterna"),
    EmojiEntry("🕯️", "candle", "vela"),
    EmojiEntry("🧯", "fire extinguisher", "extintor"),
    EmojiEntry("🧹", "broom", "escoba"),
    EmojiEntry("🧺", "basket", "cesta"),
    EmojiEntry("🧻", "roll of paper", "rollo de papel"),
    EmojiEntry("🧼", "soap", "jabón"),
    EmojiEntry("🧽", "sponge", "esponja"),
    EmojiEntry("🧴", "lotion bottle", "bote de loción"),
    EmojiEntry("🧵", "thread", "hilo"),
    EmojiEntry("🧶", "yarn", "lana"),
    EmojiEntry("🪚", "saw", "sierra"),
    EmojiEntry("🪓", "axe", "hacha"),
    EmojiEntry("🔧", "wrench", "llave inglesa"),
    EmojiEntry("⚙️", "gear", "engranaje"),
    EmojiEntry("⚖️", "balance scale", "balanza"),
    EmojiEntry("🔗", "link", "enlace"),
    EmojiEntry("🧰", "toolbox", "caja de herramientas"),
    EmojiEntry("🧲", "magnet", "imán"),
    EmojiEntry("🧪", "test tube", "tubo de ensayo"),
    EmojiEntry("🧬", "dna", "ADN"),
    EmojiEntry("🔬", "microscope", "microscopio"),
    EmojiEntry("🔭", "telescope", "telescopio"),
    EmojiEntry("📡", "satellite antenna", "antena parabólica"),
    EmojiEntry("💉", "syringe", "jeringuilla"),
    EmojiEntry("💊", "pill", "pastilla"),
    EmojiEntry("🩹", "adhesive bandage", "tirita"),
    EmojiEntry("🩺", "stethoscope", "estetoscopio"),
    EmojiEntry("🚪", "door", "puerta"),
    EmojiEntry("🪞", "mirror", "espejo"),
    EmojiEntry("🪟", "window", "ventana"),
    EmojiEntry("🛏️", "bed", "cama"),
    EmojiEntry("🛋️", "couch and lamp", "sofá y lámpara"),
    EmojiEntry("🪑", "chair", "silla"),
    EmojiEntry("🚽", "toilet", "inodoro"),
    EmojiEntry("🚿", "shower", "ducha"),
    EmojiEntry("🛁", "bathtub", "bañera"),
    EmojiEntry("🧻", "toilet paper", "papel higiénico"),
    EmojiEntry("🔑", "key", "llave"),
    EmojiEntry("🗝️", "old key", "llave antigua"),
    EmojiEntry("🔨", "hammer", "martillo"),
    EmojiEntry("🛡️", "shield", "escudo"),
    EmojiEntry("🏹", "bow and arrow", "arco y flecha"),
    EmojiEntry("🖼️", "framed picture", "cuadro"),
    EmojiEntry("🎴", "flower playing cards", "naipes de flores"),
    EmojiEntry("🃏", "joker", "comodín"),
    EmojiEntry("🔇", "muted speaker", "altavoz silenciado"),
    EmojiEntry("🔈", "speaker low volume", "altavoz volumen bajo"),
    EmojiEntry("🔊", "speaker high volume", "altavoz volumen alto"),
    EmojiEntry("📢", "loudspeaker", "megáfono"),
    EmojiEntry("📣", "megaphone", "megáfono"),
    EmojiEntry("🔔", "bell", "campana"),
    EmojiEntry("🔕", "bell with slash", "campana tachada"),
    EmojiEntry("🏧", "ATM sign", "cajero automático"),
    EmojiEntry("♿", "wheelchair symbol", "silla de ruedas"),
    EmojiEntry("🚹", "men's room", "aseo de hombres"),
    EmojiEntry("🚺", "women's room", "aseo de mujeres"),
    EmojiEntry("🚻", "restroom", "baño"),
    EmojiEntry("🚼", "baby symbol", "bebé"),
    EmojiEntry("🚾", "water closet", "aseo"),
    EmojiEntry("⚠️", "warning", "advertencia"),
    EmojiEntry("🚸", "children crossing", "niños cruzando"),
    EmojiEntry("⛔", "no entry", "prohibido el paso"),
    EmojiEntry("🚫", "prohibited", "prohibido"),
    EmojiEntry("🚳", "no bicycles", "no bicicletas"),
    EmojiEntry("🚭", "no smoking", "no fumar"),
    EmojiEntry("📵", "no mobile phones", "no móviles"),
    EmojiEntry("☢️", "radioactive", "radiactivo"),
    EmojiEntry("⬆️", "up arrow", "flecha arriba"),
    EmojiEntry("➡️", "right arrow", "flecha derecha"),
    EmojiEntry("⬇️", "down arrow", "flecha abajo"),
    EmojiEntry("⬅️", "left arrow", "flecha izquierda"),
    EmojiEntry("↕️", "up-down arrow", "flecha arriba-abajo"),
    EmojiEntry("↔️", "left-right arrow", "flecha izquierda-derecha"),
    EmojiEntry("🔃", "clockwise vertical arrows", "flechas en círculo"),
    EmojiEntry("🔙", "back arrow", "flecha atrás"),
    EmojiEntry("🔚", "end arrow", "flecha fin"),
    EmojiEntry("🔛", "on arrow", "flecha encendido"),
    EmojiEntry("🔝", "top arrow", "flecha arriba"),
    EmojiEntry("✝️", "latin cross", "cruz latina"),
    EmojiEntry("☪️", "star and crescent", "estrella y media luna"),
    EmojiEntry("☮️", "peace symbol", "símbolo de la paz"),
    EmojiEntry("🔀", "shuffle tracks button", "mezclar"),
    EmojiEntry("🔁", "repeat button", "repetir"),
    EmojiEntry("▶️", "play button", "reproducir"),
    EmojiEntry("⏩", "fast-forward button", "avance rápido"),
    EmojiEntry("⏪", "fast reverse button", "retroceso rápido"),
    EmojiEntry("⏸️", "pause button", "pausa"),
    EmojiEntry("⏹️", "stop button", "detener"),
    EmojiEntry("📶", "antenna bars", "barras de señal"),
    EmojiEntry("📳", "vibration mode", "modo vibración"),
    EmojiEntry("➗", "divide", "dividir"),
    EmojiEntry("✖️", "multiply", "multiplicar"),
    EmojiEntry("➕", "plus", "más"),
    EmojiEntry("➖", "minus", "menos"),
    EmojiEntry("❌", "cross mark", "cruz roja"),
    EmojiEntry("‼️", "double exclamation mark", "doble exclamación"),
    EmojiEntry("⁉️", "exclamation question mark", "exclamación e interrogación"),
    EmojiEntry("❓", "red question mark", "interrogación roja"),
    EmojiEntry("❗", "red exclamation mark", "exclamación roja"),
    EmojiEntry("💲", "heavy dollar sign", "símbolo de dólar"),
    EmojiEntry("🆕", "new button", "botón nuevo"),
    EmojiEntry("🆓", "free button", "botón gratis"),
    EmojiEntry("🆒", "cool button", "botón cool"),
    EmojiEntry("🆗", "OK button", "botón OK"),
    EmojiEntry("🆘", "SOS button", "botón SOS"),
    EmojiEntry("🔴", "red circle", "círculo rojo"),
    EmojiEntry("🟠", "orange circle", "círculo naranja"),
    EmojiEntry("🟡", "yellow circle", "círculo amarillo"),
    EmojiEntry("🟢", "green circle", "círculo verde"),
    EmojiEntry("🔵", "blue circle", "círculo azul"),
    EmojiEntry("🟣", "purple circle", "círculo morado"),
    EmojiEntry("⚫", "black circle", "círculo negro"),
    EmojiEntry("⚪", "white circle", "círculo blanco"),
    EmojiEntry("🏁", "chequered flag", "bandera de cuadros"),
    EmojiEntry("🚩", "triangular flag", "bandera triangular"),
    EmojiEntry("🎌", "crossed flags", "banderas cruzadas"),
    EmojiEntry("🏆", "trophy", "trofeo"),
    EmojiEntry("🏅", "sports medal", "medalla deportiva"),
    EmojiEntry("🥇", "1st place medal", "medalla de oro"),
    EmojiEntry("🥈", "2nd place medal", "medalla de plata"),
    EmojiEntry("🥉", "3rd place medal", "medalla de bronce"),
)
